language: android
dist: trusty

android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra

script:
  bash gradlew jacocoTestReportDebug jacocoTestReport ktlintCheck detekt
after_success:
  bash <(curl -s https://codecov.io/bash)
